# Análisis de Ventas — Superstore.
## 1. Importación de librerías.

In [13]:
import pandas as pd
import matplotlib.pyplot as plt

## 2. Carga del dataset

In [14]:
df = pd.read_csv('../data/train.csv', encoding='latin1')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

## 3. Exploración inicial.
## Saber cuántas filas y columnas tiene el dataset.
## Ver los tipos de datos.
## Buscar valores nulos.

In [15]:
df.shape

(9800, 18)

In [16]:
df.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code      float64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
dtype: object

In [17]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

## 4. Limpieza.
## Conversión de fechas.

In [18]:
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)

df.dtypes

Row ID                    int64
Order ID                    str
Order Date       datetime64[us]
Ship Date        datetime64[us]
Ship Mode                   str
Customer ID                 str
Customer Name               str
Segment                     str
Country                     str
City                        str
State                       str
Postal Code             float64
Region                      str
Product ID                  str
Category                    str
Sub-Category                str
Product Name                str
Sales                   float64
dtype: object

## 5. Creación de columnas nuevas.
## Extraer mes, año y calcular cuántos días tardó en enviarse cada orden..

In [ ]:
df['Mes'] = df['Order Date'].dt.month
df['Año'] = df['Order Date'].dt.year
df['Dias de Despacho'] = (df['Ship Date'] - df['Order Date']).dt.days

df[['Order Date', 'Ship Date', 'Mes', 'Año', 'Dias de Despacho']].head(10)

## 6. Agrupación de datos.
## Ventas por mes y año.

In [21]:
ventas_por_mes = df.groupby(['Año', 'Mes'])['Sales'].sum().reset_index()
ventas_por_mes.columns = ['Año', 'Mes', 'Total Ventas']
ventas_por_mes.head(40)

     Año  Mes  Total Ventas
0   2015    1    14205.7070
1   2015    2     4519.8920
2   2015    3    55205.7970
3   2015    4    27906.8550
4   2015    5    23644.3030
5   2015    6    34322.9356
6   2015    7    33781.5430
7   2015    8    27117.5365
8   2015    9    81623.5268
9   2015   10    31453.3930
10  2015   11    77907.6607
11  2015   12    68167.0585
12  2016    1    18066.9576
13  2016    2    11951.4110
14  2016    3    32339.3184
15  2016    4    34154.4685
16  2016    5    29959.5305
17  2016    6    23599.3740
18  2016    7    28608.2590
19  2016    8    36818.3422
20  2016    9    63133.6060
21  2016   10    31011.7375
22  2016   11    75249.3995
23  2016   12    74543.6012
24  2017    1    18542.4910
25  2017    2    22978.8150
26  2017    3    51165.0590
27  2017    4    38679.7670
28  2017    5    56656.9080
29  2017    6    39724.4860
30  2017    7    38320.7830
31  2017    8    30542.2003
32  2017    9    69193.3909
33  2017   10    59583.0330
34  2017   11    79066.4958
35  2017   12    95739.1210
36  2018    1    43476.4740
37  2018    2    19920.9974
38  2018    3    58863.4128
39  2018    4    35541.9101